/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import objects.Figure;
import objects.Manuf;
import objects.FigureType;
import database.modelManuf;
import database.modelFigure;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public final class EditForm extends javax.swing.JFrame {

    private Figure figure;
    private BufferedImage imgFile;
    private String tempImgPath;
    
    /**
     * Creates new form test
     */
    public EditForm() {
        figure = null;
        initComponents();
        setTypeBox();
        setManBox();
        updateBtn.setText("Add!");
        
    }
    
    public EditForm(Figure figure){
        this.figure = figure;
        initComponents();
        setTypeBox();
        setManBox();
        updateBtn.setText("Update!");
        setInitialVal();
    }
    
    private void setInitialVal(){
        nameField.setText(figure.getName());
        typeBox.getModel().setSelectedItem(figure.getType().getStringVal());
        manBox.getModel().setSelectedItem(figure.getManufacturer().getName());
        tempImgPath = figure.getImg();
        figImg.setIcon(new ImageIcon(scaleImg(tempImgPath,120,180)));
    }
    
    private ComboBoxModel setTypeBox(){
        String [] val = new String[FigureType.values().length];
        int counter = 0;
        for(FigureType i : FigureType.values()){
            val[counter] = i.getStringVal();
            counter++;
        }
        return new DefaultComboBoxModel(val);
    }
    
    private ComboBoxModel setManBox(){
        modelManuf m = new modelManuf();
        ArrayList<Manuf> listM = m.getManufacturers();
        String [] val = new String[listM.size()];
        int counter = 0 ;
        for(Manuf i : listM){
            val[counter] = i.getName();
            counter++;
        }
        return new DefaultComboBoxModel(val);
    }
    
    private Image scaleImg(String img_path, int width, int height){
        try{
            imgFile = ImageIO.read(getClass().getResource("/img/"+img_path));
            Image dimg = imgFile.getScaledInstance(width, height, Image.SCALE_SMOOTH);
            return dimg;
        }catch (IOException e){
            e.printStackTrace();
            return null;
        }
    }
    
    private Image scaleImg(File img_file, int width, int height){
        try{
            imgFile = ImageIO.read(img_file);
            Image dimg = imgFile.getScaledInstance(width, height, Image.SCALE_SMOOTH);
            return dimg;
        }catch (IOException e){
            e.printStackTrace();
            return null;
        }
    }
    
    private void importImage(String img_path){
        try{
            String path = "build/classes/img/"+img_path;
            File F = new File(path);
            if(F.createNewFile()){
                ImageIO.write(imgFile, img_path.substring(img_path.lastIndexOf(".") + 1), F);
            }
            path = "src/img/"+img_path;
            F = new File(path);
            if(F.createNewFile()){
                ImageIO.write(imgFile, img_path.substring(img_path.lastIndexOf(".") + 1), F);
            }
        } catch (IOException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageChooser = new javax.swing.JFileChooser();
        figImg = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        manLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        typeBox = new javax.swing.JComboBox<>();
        manBox = new javax.swing.JComboBox<>();
        imgBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        figImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nameLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        nameLabel.setText("Name :");

        typeLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        typeLabel.setText("Type :");

        manLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        manLabel.setText("Manufacturer :");

        typeBox.setModel(setTypeBox());
        typeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeBoxActionPerformed(evt);
            }
        });

        manBox.setModel(setManBox());

        imgBtn.setText("change");
        imgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("jButton3");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(imgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(figImg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(typeLabel)
                                    .addComponent(manLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameField)
                                    .addComponent(typeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(manBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(typeLabel)
                        .addGap(4, 4, 4)
                        .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(manLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(figImg, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelBtn)
                    .addComponent(updateBtn))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeBoxActionPerformed

    private void imgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgBtnActionPerformed

        imageChooser.setDialogTitle("Choose an Image!");
        imageChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = imageChooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            File F = imageChooser.getSelectedFile();
            tempImgPath = F.getName();
            figImg.setIcon(new ImageIcon(scaleImg(F, 120,180)));
        }
        
    }//GEN-LAST:event_imgBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        modelFigure F = new modelFigure();
        modelManuf M = new modelManuf();

        if(figure != null){
            figure.setName(nameField.getText());
            figure.setType(typeBox.getModel().getSelectedItem().toString());
            figure.setImg(tempImgPath);
            figure.setManufacturer(M.getManufacturer(manBox.getModel().getSelectedItem().toString()));
            importImage(figure.getImg());
            int check = F.updateFigure(figure);
            if(check > 0){
                dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Gagal update");
            }
        }
        else{
            importImage(tempImgPath);
            int check = F.insertFigure(
                    nameField.getText(), 
                    typeBox.getModel().getSelectedItem().toString(),
                    tempImgPath,
                    M.getManufacturer(manBox.getModel().getSelectedItem().toString())
                    );
            if(check > 0){
                dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Gagal add");
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel figImg;
    private javax.swing.JFileChooser imageChooser;
    private javax.swing.JButton imgBtn;
    private javax.swing.JComboBox<String> manBox;
    private javax.swing.JLabel manLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox<String> typeBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
