/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

import objects.Figure;

/**
 *
 * @author User
 */
public class FigureCard extends javax.swing.JPanel {

    
    private Figure figure;
    
    /**
     * Creates new form figureCard
     */
    public FigureCard() {
        initComponents();
    }
    
    public FigureCard(Figure figure) {
        this.figure = figure;
        initComponents();
        setDisplay();
    }
    
    private void setDisplay(){
        nameVal.setText(figure.getName());
        typeVal.setText(figure.getType().getStringVal());
        manufVal.setText(figure.getManufacturer().getName());
        Image temp = scaleImg(figure.getManufacturer().getImgPath(), 90, 30);
        if(temp != null){
            manufLogo.setIcon(new ImageIcon(temp));
        }
        else{
            System.out.println("null");
        }
        
        temp = scaleImg(figure.getImg(), 120, 180);
        if(temp != null){
            figImg.setIcon(new ImageIcon(temp));
        }
        else{
            System.out.println("null");
        }
    }
    
    private Image scaleImg(String img_path, int width, int height){
        try{
            BufferedImage img = ImageIO.read(getClass().getResource("/img/"+img_path));
            Image dimg = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
            return dimg;
        }catch (IOException e){
            return null;
        }
    }
    
    public void refresh(){
        Listing L = (Listing) this.getTopLevelAncestor();
        L.refresh();
    }
    
    public void windowClosed(WindowEvent e){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nameVal = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        typeVal = new javax.swing.JLabel();
        manufLabel = new javax.swing.JLabel();
        manufVal = new javax.swing.JLabel();
        manufLogo = new javax.swing.JLabel();
        figImg = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        nameVal.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        nameVal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameVal.setText("jLabel2");

        typeLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        typeLabel.setText("Type :");

        typeVal.setText("jLabel4");

        manufLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        manufLabel.setText("Manufacturer :");

        manufVal.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        manufVal.setText("jLabel6");

        figImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(figImg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeVal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeLabel)
                            .addComponent(manufLabel)
                            .addComponent(manufVal)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton1)
                                .addGap(37, 37, 37)
                                .addComponent(jButton2)))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manufLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manufLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameVal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(typeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeVal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manufLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manufVal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(figImg, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int opt = JOptionPane.showConfirmDialog(null, "Delete?","Delete", JOptionPane.YES_NO_OPTION);
        if (opt == 0){
            Listing L = (Listing) this.getTopLevelAncestor();
            L.getFigModel().deleteFigure(figure.getId());
            refresh();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EditForm edit = new EditForm(figure);
        edit.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        JDialog e = new JDialog(edit, "Edit Form",true);
        e.getContentPane().add(edit.getContentPane(), BorderLayout.CENTER);
        e.pack();
        e.addWindowListener(new WindowAdapter(){
            public void WindowClosed(WindowEvent e){
                refresh();
            }
            
        });
        e.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel figImg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel manufLabel;
    private javax.swing.JLabel manufLogo;
    private javax.swing.JLabel manufVal;
    private javax.swing.JLabel nameVal;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel typeVal;
    // End of variables declaration//GEN-END:variables
}
