/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import objects.Manuf;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class ManufCard extends javax.swing.JPanel {

    private Manuf man;
    
    /**
     * Creates new form ManufCard
     */
    public ManufCard(Manuf man) {
        this.man = man;
        initComponents();
        setDisplay();
    }
    
    private void setDisplay(){
        nameVal.setText(man.getName());
        Image temp = scaleImg(man.getImgPath(), 200, 50);
        if(temp != null){
            manLogo.setIcon(new ImageIcon(temp));
        }
        numVal.setText(String.valueOf(man.getNFigure()));
        
    }
    
    private Image scaleImg(String img_path, int width, int height){
        try{
            BufferedImage img = ImageIO.read(getClass().getResource("/img/"+img_path));
            Image dimg = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
            return dimg;
        }catch (IOException e){
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manLogo = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameVal = new javax.swing.JLabel();
        numLabel = new javax.swing.JLabel();
        numVal = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nameLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        nameLabel.setText("Name :");

        nameVal.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nameVal.setText("jLabel3");

        numLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        numLabel.setText("Number of Figures :");

        numVal.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        numVal.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(nameVal))
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numVal)
                            .addComponent(numLabel)))
                    .addComponent(manLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(numLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameVal)
                    .addComponent(numVal))
                .addGap(82, 82, 82))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel manLogo;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameVal;
    private javax.swing.JLabel numLabel;
    private javax.swing.JLabel numVal;
    // End of variables declaration//GEN-END:variables
}
